#!/usr/bin/env node

/**
 * AIC - Direct execution wrapper
 * This allows running aic commands without global installation
 */

const path = require('path');
const { spawn } = require('child_process');

// Get the directory where this script is located
const scriptDir = __dirname;
const aicScript = path.join(scriptDir, 'bin', 'aic.js');

// Pass all arguments to the actual aic.js script
const args = process.argv.slice(2);
const child = spawn('node', [aicScript, ...args], {
  stdio: 'inherit',
  cwd: scriptDir
});

child.on('exit', (code) => {
  process.exit(code);
});

child.on('error', (error) => {
  console.error('Error running aic:', error.message);
  process.exit(1);
});