#!/usr/bin/env node

/**
 * AICOMMIT - Direct execution wrapper
 * This allows running aicommit commands without global installation
 */

const path = require('path');
const { spawn } = require('child_process');

// Get the directory where this script is located
const scriptDir = __dirname;
const aicommitScript = path.join(scriptDir, 'bin', 'aicommit.js');

// Pass all arguments to the actual aicommit.js script
const args = process.argv.slice(2);
const child = spawn('node', [aicommitScript, ...args], {
  stdio: 'inherit',
  cwd: scriptDir
});

child.on('exit', (code) => {
  process.exit(code);
});

child.on('error', (error) => {
  console.error('Error running aicommit:', error.message);
  process.exit(1);
});